// <auto-generated />
using System;
using BudgetPlanner.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251207172719_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.BudgetPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<Guid?>("PrognosisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Recurring")
                        .HasColumnType("int");

                    b.Property<Guid?>("RecurringId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PrognosisId");

                    b.ToTable("BudgetPosts");
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Alla"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mat"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Kläder"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Skatt"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hem"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hobby"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Barn"
                        },
                        new
                        {
                            Id = 9,
                            Name = "TV"
                        },
                        new
                        {
                            Id = 10,
                            Name = "SaaS"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Prenumerationer"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Husdjur"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Underhållning"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Lön"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Bidrag"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Extrainkomst"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Okänd"
                        });
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.Prognosis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("FromDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MonthlyExpense")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MonthlyIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ToDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Prognoses");
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.RecurringBudgetPostTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PostType")
                        .HasColumnType("int");

                    b.Property<int>("Recurring")
                        .HasColumnType("int");

                    b.Property<Guid>("RecurringId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("RecurringStartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("RecurringPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2500.0,
                            CategoryId = 8,
                            Description = "Barnbidrag",
                            PostType = 0,
                            Recurring = 3,
                            RecurringId = new Guid("389904d6-c94c-4bd8-8864-27644219f5ad"),
                            RecurringStartDate = new DateTime(2024, 1, 23, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Amount = 8500.0,
                            CategoryId = 6,
                            Description = "Hyra",
                            PostType = 1,
                            Recurring = 3,
                            RecurringId = new Guid("704d48ad-aa50-44fd-a0ca-8f0b59266f30"),
                            RecurringStartDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1200.0,
                            CategoryId = 3,
                            Description = "Busskort",
                            PostType = 1,
                            Recurring = 3,
                            RecurringId = new Guid("783157fe-c960-43cc-b490-66ac6ca8fad7"),
                            RecurringStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Amount = 750.0,
                            CategoryId = 3,
                            Description = "Resor till arbete",
                            PostType = 1,
                            Recurring = 3,
                            RecurringId = new Guid("30d8676b-de2f-4cf9-90af-18adf034feb5"),
                            RecurringStartDate = new DateTime(2024, 1, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Amount = 900.0,
                            CategoryId = 15,
                            Description = "Studiebidrag",
                            PostType = 0,
                            Recurring = 3,
                            RecurringId = new Guid("5a36fbcd-47f9-4753-9c16-91d1dbd9eaab"),
                            RecurringStartDate = new DateTime(2024, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Amount = 3200.0,
                            CategoryId = 2,
                            Description = "Veckohandling",
                            PostType = 1,
                            Recurring = 2,
                            RecurringId = new Guid("810421e0-9578-4959-a5e6-0af399ab0cdf"),
                            RecurringStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1200.0,
                            CategoryId = 11,
                            Description = "Netflix + Spotify",
                            PostType = 1,
                            Recurring = 3,
                            RecurringId = new Guid("19cf7680-db76-4047-bb8b-79217df278c1"),
                            RecurringStartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Amount = 4500.0,
                            CategoryId = 3,
                            Description = "Bilskatt",
                            PostType = 1,
                            Recurring = 4,
                            RecurringId = new Guid("67f4ec7c-13a9-4973-a884-80b009b9f3b0"),
                            RecurringStartDate = new DateTime(2024, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.StoppedRecurring", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RecurringId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StoppedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("StoppedRecurringPosts");
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.BudgetPost", b =>
                {
                    b.HasOne("BudgetPlanner.DomainLayer.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetPlanner.DomainLayer.Models.Prognosis", null)
                        .WithMany("BudgetPosts")
                        .HasForeignKey("PrognosisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.RecurringBudgetPostTemplate", b =>
                {
                    b.HasOne("BudgetPlanner.DomainLayer.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.Prognosis", b =>
                {
                    b.Navigation("BudgetPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
