// <auto-generated />
using System;
using BudgetPlanner.DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BudgetPlanner.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.BudgetPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("float(18)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PrognosisId")
                        .HasColumnType("int");

                    b.Property<int>("Reccuring")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PrognosisId");

                    b.ToTable("BudgetPosts");
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Transport"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Clothing"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Taxes"
                        },
                        new
                        {
                            Id = 5,
                            Name = "House"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hobbies"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Kids"
                        },
                        new
                        {
                            Id = 8,
                            Name = "TV"
                        },
                        new
                        {
                            Id = 9,
                            Name = "SaaS"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Subscriptions"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Salary"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Allowance"
                        },
                        new
                        {
                            Id = 13,
                            Name = "ExtraIncome"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Undefined"
                        });
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.Prognosis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalExpenses")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalSum")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Prognoses");
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.BudgetPost", b =>
                {
                    b.HasOne("BudgetPlanner.DomainLayer.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BudgetPlanner.DomainLayer.Models.Prognosis", null)
                        .WithMany("BudgetPosts")
                        .HasForeignKey("PrognosisId");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("BudgetPlanner.DomainLayer.Models.Prognosis", b =>
                {
                    b.Navigation("BudgetPosts");
                });
#pragma warning restore 612, 618
        }
    }
}
